---
# tasks file for pve_qemu
- name: Get Initial Cluster Resources
  shell: "/usr/bin/pvesh get /cluster/resources -type=vm --output-format json"
  register: resources_initial
  changed_when: false

- import_tasks: destroy.yml
  when:
    - pve_qemu.state == 'absent'
    - (resources_initial.stdout | from_json | selectattr('vmid', 'equalto', pve_qemu.vmid) | first) is defined

- import_tasks: clone.yml
  when:
    - pve_qemu.state != 'absent'
    - (resources_initial.stdout | from_json | selectattr('vmid', 'equalto', pve_qemu.vmid) | first) is not defined

- import_tasks: configuration.yml
  when: pve_qemu.state != 'absent'
