---
# tasks file for pve_qemu
- import_tasks: pve_qemu-check.yml
  tags:
    - check
    - pve_qemu:check

- name: Get Cluster Resources
  shell: "pvesh get /cluster/resources -type=vm --output-format json"
  register: resources
  changed_when: false

- debug:
    msg: "{{ resources.stdout }}"

- import_tasks: pve_qemu-provision_clone.yml
  when:
    - pve_qemu.template_id is defined
    - resources.stdout | from_json | selectattr('vmid', 'equalto', pve_qemu.vmid) | first is not defined
  tags:
    - pve_qemu:provision