---
# tasks file for pve_qemu
- import_tasks: pve_qemu-check.yml
  tags:
    - check
    - pve_qemu:check

- name: Get Cluster Resources
  shell: "pvesh get /cluster/resources -type=vm --output-format json"
  register: resources
  
- import_tasks: pve_qemu-provision_clone.yml
  when:
    - pve_qemu.template_id is defined
    - pve_qemu.vmid|string in resources.stdout
  tags:
    - pve_qemu:provision